### ISSUE TITLE
Ingress' annotationsRasaX not getting applied

### ISSUE THREAD

**Issue by b-quachtran** [RasaHQ/rasa-x-helm#124]
When running `helm template`, the annotations specified under `annotationsRasaX` in `Ingress:` don't get applied. 

Ingress Annotation:
```
ingress:
  # enabled should be `true` if you want to use this ingress.
  # Note that if `nginx.enabled` is `true` the `rasa/nginx` image is used as reverse proxy.
  # In order to use nginx ingress you have to set `nginx.enabled=false`.
  enabled: true
  # annotations for the ingress - annotations are applied for the rasa and rasax ingresses
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  # annotationsRasa is extra annotations for the rasa nginx ingress
  annotationsRasa: {}
  # annotationsRasaX is extra annotations for the rasa x nginx ingress
  annotationsRasaX:
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
```

`helm template` output:
```
# Source: rasa-x/templates/ingress.yaml
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: RELEASE-NAME-rasa-x
  labels:
    helm.sh/chart: rasa-x-1.7.12
    app.kubernetes.io/name: rasa-x
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/version: "0.33.0"
    app.kubernetes.io/managed-by: Helm
```

When these annotations get moved to `annotations:` in `Ingress:`, however, they do work:

```
# ingress settings
ingress:
  # enabled should be `true` if you want to use this ingress.
  # Note that if `nginx.enabled` is `true` the `rasa/nginx` image is used as reverse proxy.
  # In order to use nginx ingress you have to set `nginx.enabled=false`.
  enabled: true
  # annotations for the ingress - annotations are applied for the rasa and rasax ingresses
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  # annotationsRasa is extra annotations for the rasa nginx ingress
  annotationsRasa: {}
  # annotationsRasaX is extra annotations for the rasa x nginx ingress
  annotationsRasaX: {}
```

`helm template` output:
```
# Source: rasa-x/templates/ingress.yaml
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: RELEASE-NAME-rasa-x
  labels:
    helm.sh/chart: rasa-x-1.7.12
    app.kubernetes.io/name: rasa-x
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/version: "0.33.0"
    app.kubernetes.io/managed-by: Helm
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
```
