### ISSUE TITLE
Add support for volumeName & volumeMode to values.yml

### ISSUE THREAD

**Issue by rgstephens** [RasaHQ/rasa-x-helm#147]
Would like to specify `volumeName` and `volumeMode` in `values.yml`

```yml
spec:
  volumeName: pv.vol.name
  storageClassName: ''
  volumeMode: Filesystem
  resources:
    requests:
      storage: 5Gi
```
