### ISSUE TITLE
Not able to override fsGroup for rabbit

### ISSUE THREAD

**Issue by rgstephens** [RasaHQ/rasa-x-helm#154]
Tried the following to set fsGroup to null but it didn't work:

```yml
rabbitmq:
  rabbitmq:
    securityContext:
      enabled: true
      fsGroup: null
```

**Comment by ferenc-hechler** [comment]
We had problems with Open-Shift and the user-/group-ids. 
The trick was to set securityContext.enabled to false:

```
rabbitmq:
    securityContext:
      enabled: false

redis:
    securityContext:
      enabled: false
```

Also we set the value on the commandline "--set securityContext.fsGroup=null"

The PostgreSQL is not installed with the rasa-x helm chart (postgresql.install=false).

Instead of, we used the bitnamy/postgresql chart with the following values:
```
containerSecurityContext:
  enabled: false
securityContext:
  enabled: false
# create an initial schema
postgresqlDatabase: "rasa"
```

Maybe this might also help others.   :-)
