### ISSUE TITLE
Add Support for NetworkPolicy

### ISSUE THREAD

**Issue by rgstephens** [RasaHQ/rasa-x-helm#160]
Add support for `NetworkPolicy` configuration similar to [bitnami Postgres](https://github.com/bitnami/charts/tree/master/bitnami/postgresql) chart.

But instead of the bitnami `allowExternal`, for highly secure environments where all internal namespace connections are disabled by default, need to add the ability generate explicit ingress & egress policies for each of the required connections.  For example:

```yml
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: egress-from-event-service-to-postgresql
spec:
  policyTypes:
    - Egress
  podSelector:
    matchLabels:
      app.kubernetes.io/component: event-service # Source
  egress:
    - to:
      - podSelector:
          matchLabels:
              app: postgresql # Destination
      ports:
      - protocol: TCP
        port: 5432
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: ingress-from-event-service-to-postgresql
spec:
  policyTypes:
    - Ingress
  podSelector:
   matchLabels:
      app: postgresql # Destination
  ingress:
    - from:
      - podSelector:
          matchLabels:
              app.kubernetes.io/component: event-service # Source
      ports:
      - protocol: TCP
        port: 5432
```

@tczekajlo To support this, what about following values.yml:

```yml
networkPolicy:
  enabled: false
  # The Policy model to apply. When set to false, explicit ingress & egress
  # network policies will be generated for the required inter-pod connections
  # When true, pods will accept connections from any source
  # (with the correct destination port).
  allowExternal: true
  explicitNamespacesSelector: {}
```

**Comment by tczekajlo** [comment]
@rgstephens I assume we do this for all services not only for the event-service?

**Comment by rgstephens** [comment]
Yes, it would generate for all combinations of service ingress/egress

**Comment by tczekajlo** [comment]
> Yes, it would generate for all combinations of service ingress/egress

👍🏻

**Comment by rgstephens** [comment]
Implementing it as follows:

```yml
networkPolicy:
  # Enable creation of NetworkPolicy resources. When set to true, explicit ingress & egress
  # network policies will be generated for the required inter-pod connections
  enabled: false
```

If you enable the policy, it will create 36 `NetworkPolicy` configs:

```yml
  name: egress-from-rasa-x-to-rasa-production
  name: ingress-from-rasa-x-to-rasa-production
  name: egress-from-rasa-production-to-rasa-x
  name: ingress-from-rasa-production-to-rasa-x
  name: egress-from-rasa-worker-to-rasa-x
  name: ingress-from-rasa-worker-to-rasa-x
  name: egress-from-rasa-production-to-redis
  name: ingress-from-rasa-production-to-redis
  name: egress-from-rasa-production-to-app
  name: ingress-from-rasa-production-to-app
  name: egress-from-rasa-x-to-rasa-worker
  name: ingress-from-rasa-x-to-rasa-worker
  name: egress-from-rasa-x-to-event-service
  name: ingress-from-rasa-x-to-event-service
  name: egress-from-event-service-to-postgresql
  name: ingress-from-event-service-to-postgresql
  name: egress-from-rasa-worker-to-postgresql
  name: ingress-from-rasa-worker-to-postgresql
  name: egress-from-rasa-production-to-postgresql
  name: ingress-from-rasa-production-to-postgresql
  name: egress-from-rasa-x-to-postgresql
  name: ingress-from-rasa-x-to-postgresql
  name: egress-from-event-service-to-rabbitmq
  name: ingress-from-event-service-to-rabbitmq
  name: egress-from-rasa-worker-to-rabbitmq
  name: ingress-from-rasa-worker-to-rabbitmq
  name: egress-from-rasa-production-to-rabbitmq
  name: ingress-from-rasa-production-to-rabbitmq
  name: egress-from-rasa-x-to-rabbitmq
  name: ingress-from-rasa-x-to-rabbitmq
  name: egress-from-rasa-production-to-duckling
  name: ingress-from-rasa-production-to-duckling
  name: egress-from-nginx-to-rasa-production
  name: ingress-from-nginx-to-rasa-production
  name: egress-from-nginx-to-rasa-x
  name: ingress-from-nginx-to-rasa-x
```

If any of the following are `false`, it will not generate NetworkPolicies associated with that service:

```yml
postgresql.install
rabbitmq.install
duckling.enabled
nginx.enabled
```
