### ISSUE TITLE
Comment changes in the values file

### ISSUE THREAD

**Issue by kronos-cm** [RasaHQ/rasa-x-helm#187]
Correcting the comments of `livenessProbe` and `readinessProbe`

Example from:
```
  # livenessProbe checks whether rasa x needs to be restarted
  livenessProbe:
    # initialProbeDelay for the `readinessProbe`
    initialProbeDelay: 10
    # scheme to be used by the `readinessProbe`
    scheme: "HTTP"
  # readinessProbe checks whether rasa x can receive traffic
  readinessProbe:
    # initialProbeDelay for the `readinessProbe`
    initialProbeDelay: 10
    # scheme to be used by the `readinessProbe`
    scheme: "HTTP"
```
to:
```
  # livenessProbe checks whether rasa x needs to be restarted
  livenessProbe:
    # initialProbeDelay for the `livenessProbe`
    initialProbeDelay: 10
    # scheme to be used by the `livenessProbe`
    scheme: "HTTP"
  # readinessProbe checks whether rasa x can receive traffic
  readinessProbe:
    # initialProbeDelay for the `readinessProbe`
    initialProbeDelay: 10
    # scheme to be used by the `readinessProbe`
    scheme: "HTTP"
```
And make the order consistent so that always `livenessProbe` appears first across services
