### ISSUE TITLE
Latest Release breaks updates / installations into the same namespace

### ISSUE THREAD

**Issue by loomsen** [RasaHQ/rasa-x-helm#195]
Hi,

the latest update to the helm chart  (1.10.2) breaks our deployment. It seems like a `helm delete` did not delete the `rasa-x-rasa-open-source` ingress definition, as it is not part of the helm chart anymore, thus breaking the installation due to the dangling object in the same namespace.
It was the same for an upgrade as well as a fresh installation after running `helm delete` in an already existing namespace. So only installations into a new namespace work.

```
$ helm upgrade -i rasa-x rasa-x/rasa-x -f deployment/rasa-x/values.yaml --namespace ${namespace} --create-namespace\
 --set rasax.initialUser.password="$password" \
--set ingress.hosts[0].host=$deployment_url \
--set ingress.tls[0].hosts[0]=$deployment_url \
--set ingress.tls[0].secretName=$CI_COMMIT_REF_SLUG-tls \
--set rasa.tag=$CI_COMMIT_SHA \
--set app.tag=$CI_COMMIT_SHA \
--set rasa.extraArgs[0]="--debug" \
--set app.args[0]="start" \
--set app.args[1]="--actions" \
--set app.args[2]="actions" \
--set app.args[3]="--debug" \
--wait \
--set dbMigrationService.initContainer.image="alpine@sha256:3c7497bf0c7af93428242d6176e8f7905f2201d8fc5861f45be7a346b5f23436" \
--timeout 1200s
Release "rasa-x" does not exist. Installing it now.
Error: admission webhook "validate.nginx.ingress.kubernetes.io" denied the request: host "rasa-x.example.de" and path "/core/(.*)" is already defined in ingress rasa-x/rasa-x-rasa-open-source
```

Here's the values file:

```
rasax:
  tag: "0.38.1"
  resources:
    requests:
      cpu: 1
      memory: 1Gi
    limits:
      cpu: 1
      memory: 4Gi

rasa:
  versions:
    rasaProduction:
      resources:
        requests:
          cpu: 2
          memory: 2Gi
        limits:
          cpu: 4
          memory: 12Gi
    rasaWorker:
      resources:
        requests:
          cpu: 2
          memory: 4Gi
        limits:
          cpu: 4
          memory: 12Gi
  name: example.azurecr.io/rasa/rasa
  # token Rasa accepts as authentication token from other Rasa services
  token: "secretToken"
  # rabbitQueue it should use to dispatch events to Rasa X
  rabbitQueue: "rasa_production_events"
  additionalChannelCredentials:
    channels.aurasa.AurasaChannel:


separateEventService: "false"


app:
  name: example.azurecr.io/rasa/rasa-app
  resources:
    requests:
      cpu: 0.5
      memory: 200Mi
    limits:
      cpu: 1
      memory: 1Gi
  # additional volumeMounts to the main container
  extraVolumeMounts:
  - name: usecase-config
    mountPath: /app/usecase-config.yml
    subPath: usecase-config.yml
  # additional volumes to the pod
  extraVolumes:
  - name: usecase-config
    configMap:
      name: usecase-config
      items:
      - key: usecase-config.yml
        path: usecase-config.yml


nginx:
  enabled: false
  service:
    type: ClusterIP
  resources:
    requests:
      cpu: 0.2
      memory: 200Mi
    limits:
      cpu: 0.2
      memory: 200Mi

duckling:
  resources:
    requests:
      cpu: 0.5
      memory: 200Mi
    limits:
      cpu: 1
      memory: 1Gi

postgresql:
  master:
    resources:
      requests:
        cpu: 1
        memory: 250Mi
      limits:
        cpu: 1
        memory: 350Mi


rabbitmq:
  resources:
    requests:
      cpu: 0.2
      memory: 250Mi
    limits:
      cpu: 0.5
      memory: 1Gi


redis:
  install: true
  resources:
    requests:
      cpu: 0.2
      memory: 250Mi
    limits:
      cpu: 0.5
      memory: 350Mi
  redis:
    password: "password"


ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod-http01
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"


images:
  pullPolicy: "Always"
  imagePullSecrets:
    - name: "regcred"
```
