### ISSUE TITLE
Liveness probe fails if "@" present in RabbitMQ password

### ISSUE THREAD

**Issue by kaiogu** [RasaHQ/rasa-x-helm#221]
My containers have been restarting because curl seems to be parsing the password incorrectly.

These are the events I'm getting:
![image](https://user-images.githubusercontent.com/32000243/127176197-0efbfa7e-c3c4-477d-9beb-485f3ae34005.png)

While this is the password:
```yaml
rabbitmq:
    # rabbitmq settings of the subchart
    rabbitmq:
        # password which is used for the authentication
        password: "3jv@5r!PqEsnM*J%MpK"
```

So the password is parsed in a strange way and the part before the @ is interpreted as the user and the part behind it is interpreted as the target host. 

`3jv@5r!PqEsnM*J%MpK` is interpreted as `user@host`.

Either the curl liveness and readiness probes need to be fixed or the rabbitMQ password validation in the Helm Chart needs to dissalow `@`.
