### ISSUE TITLE
Decouple rasa/nginx and make it optional in favor of Ingress

### ISSUE THREAD

**Issue by rafi** [RasaHQ/rasa-x-helm#32]
Great work on the chart, big improvements since my older fork, especially around decoupling rabbitmq, redis, rabbitmq to official sub-charts and general normalization. However `rasa/nginx` image deployment is still required as rasa distributed network system proxy.

What's the reason of requiring nginx as a reverse-proxy for the Rasa system? I use the official k8s nginx-ingress controller for all my cluster networking, and I want to refrain from adding another container and networking layer.

I've had to dig in `rasa/nginx:latest` image (Where is the `Dockerfile`?) and convert `/opt/bitnami/nginx/conf/conf.d/rasax.nginx` to Kubernetes 1st-class citizen Ingress objects with all the appropriate rewrites and custom snippets and made rasa/nginx optional.

```txt
INGRESS                HOSTS               PATHS        SERVICES
+------                +----               +----        +-------
rasa-app               bot.foobar.com      /app/(.*)    app:5055
rasa-core-production   bot.foobar.com      /core/(.*)   rasa-production:5005
rasa-core-socket       bot.foobar.com      /socket.io   rasa-production:5005
rasa-x                 bot.foobar.com      /            rasa-x:5002
rasa-x-chat            bot.foobar.com      /api/chat    rasa-x:5002
```

```yaml
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: rasa-app
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
  - host: bot.foobar.com
    http:
      paths:
      - backend:
          serviceName: app
          servicePort: 5055
        path: /app/(.*)

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: rasa-core-production
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
  - host: bot.foobar.com
    http:
      paths:
      - backend:
          serviceName: rasa-production
          servicePort: 5005
        path: /core/(.*)

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/proxy-buffering: "off"
    nginx.ingress.kubernetes.io/proxy-http-version: "1.1"
  name: rasa-core-socket
spec:
  rules:
  - host: bot.foobar.com
    http:
      paths:
      - backend:
          serviceName: rasa-production
          servicePort: 5005
        path: /socket.io

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: rasa-x
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
spec:
  rules:
  - host: bot.foobar.com
    http:
      paths:
      - backend:
          serviceName: rasa-x
          servicePort: 5002
        path: /

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: rasa-x-chat
  annotations:
    nginx.ingress.kubernetes.io/configuration-snippet: |
      if ($arg_environment = "") {
          rewrite ^ /core/webhooks/rasa/webhook last;
      }
      if ($arg_environment = "production") {
          rewrite ^ /core/webhooks/rasa/webhook last;
      }
spec:
  rules:
  - host: bot.foobar.com
    http:
      paths:
      - backend:
          serviceName: rasa-x
          servicePort: 5002
        path: /api/chat
```
