### ISSUE TITLE
make Redis installation optional

### ISSUE THREAD

**Issue by loomsen** [RasaHQ/rasa-x-helm#67]
If we disable redis installation, the charts render unusable. In order to make this work, some changes need to be made to the templates.

If redis installation disabled, there will be a missing key error:

Rendered `rasa-deployments.yaml`:

```
[...]
        - name: "REDIS_PASSWORD"
          valueFrom:
            secretKeyRef:
              name: "rasa-x-redis"
              key: 
[...]
```
