### ISSUE TITLE
Add support for Jaeger sidecar annotation and additional endpoints

### ISSUE THREAD

**Issue by rgstephens** [RasaHQ/rasa-x-helm#88]
Add support for the Jaeger sidecar [annotation](https://www.jaegertracing.io/docs/1.20/operator/#auto-injecting-jaeger-agent-sidecars) used by the [Jaeger Kubernetes Operator](https://www.jaegertracing.io/docs/1.20/operator/).

```yml
rasa:
  jaegerSidecar: "true"

rasax:
  jaegerSidecar: "true"

app:
  jaegerSidecar: "true"
```

Also add the ability to include additional endpoints to the rasa `endpoints.yml` config.

```yml
rasa:
  additionalEndpoints:
     telemetry:
        type: jaeger
        service_name: rasa
```
